version: "3.8"

services:
  db:
    image: mysql:5.7
    container_name: db
    environment:
      MYSQL_ROOT_PASSWORD: 17072027
      MYSQL_DATABASE: l2jdb
      MYSQL_USER: gereiz
      MYSQL_PASSWORD: 17072027
    volumes:
      - ./sl2/db_installer/.my.cnf:/root/.my.cnf
      - ./sl2/db_installer/install_db.sh:/docker-entrypoint-initdb.d/install_db.sh
      - ./mysql:/var/lib/mysql
    ports:
      - "3307:3306"  # Porta externa 3307 → interna 3306
    networks:
      - ntw
    restart: always

  sl2:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sl2
    networks:
      - ntw
    ports:
      - "9014:9014"
      - "2106:2106"
      - "7777:7777"
    depends_on:
      - db
    restart: always

networks:
  ntw:
    driver: bridge
